import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Dash={market_count:number;first_priority_market_count:number;diagnosis_request_count:number;overseas_camp_count:number;translation_task_count:number;overseas_review_count:number;active_market_count:number}
type Market={country_code:string;country_name:string;priority_group:string;primary_language:string;supported_languages:string[]|null;target_keywords:string[]|null;status:string;market_notes:string|null}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{dash:null as Dash|null,markets:[] as Market[],error:'supabase_not_configured'};const[d,m]=await Promise.all([s.from('global_expansion_dashboard').select('*').maybeSingle(),s.from('global_markets').select('*').order('priority_group').order('country_name')]);return{dash:d.data as Dash|null,markets:(m.data||[]) as Market[],error:d.error?.message||m.error?.message||null}}
export default async function GlobalExpansionPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{dash,markets,error}=await loadData();const q=`?token=${encodeURIComponent(token)}`;return <div className="space-y-6"><div className="rounded-3xl bg-sky-950 p-6 text-white"><p className="text-xs font-bold text-sky-200">Phase16 Global Expansion</p><h2 className="mt-2 text-3xl font-black">世界展開ダッシュボード</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-sky-100">谷田部メソッドOSを、日本国内向け事業から世界中の選手と保護者が使う診断プラットフォームへ拡張します。</p><div className="mt-5 flex flex-wrap gap-2">{[['海外診断','global-diagnosis'],['海外キャンプ','overseas-camps'],['AI通訳','ai-translation'],['サッカー病院','soccer-hospital']].map(([l,path])=><Link key={path} href={`/admin/ai-secretary/${path}${q}`} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-sky-950">{l}</Link>)}</div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-4"><Kpi label="対象国" value={dash?.market_count??0}/><Kpi label="第一優先国" value={dash?.first_priority_market_count??0}/><Kpi label="海外診断" value={dash?.diagnosis_request_count??0}/><Kpi label="海外キャンプ" value={dash?.overseas_camp_count??0}/><Kpi label="AI通訳" value={dash?.translation_task_count??0}/><Kpi label="海外レビュー" value={dash?.overseas_review_count??0}/><Kpi label="稼働国" value={dash?.active_market_count??0}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">優先国とSEOキーワード</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{markets.map(m=><article key={m.country_code} className="rounded-xl bg-gray-50 p-4"><div className="flex items-center gap-2"><span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-black text-sky-800">{m.priority_group}</span><span className="text-xs font-bold text-gray-500">{m.primary_language}</span><span className="text-xs font-bold text-gray-500">{m.status}</span></div><h4 className="mt-2 font-black text-gray-900">{m.country_name}</h4><p className="mt-1 text-xs text-gray-500">対応言語: {(m.supported_languages||[]).join(', ')}</p><div className="mt-2 flex flex-wrap gap-2">{(m.target_keywords||[]).map(k=><span key={k} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-gray-700">{k}</span>)}</div><p className="mt-2 text-sm leading-6 text-gray-700">{m.market_notes}</p></article>)}</div></section></div>}
function Kpi({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-sky-200 bg-sky-50 p-5 text-sky-950"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
