import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Entry={id:string;display_name:string;entry_type:string;country:string|null;region:string|null;city:string|null;service_types:string[]|null;certification_rank:string;referral_priority:number;contact_policy:string|null;public_profile_status:string;notes:string|null;tenant_name:string|null;coach_score:number|null;school_retention_rate:number|null;school_improvement_rate:number|null}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Entry[],error:'supabase_not_configured'};const{data,error}=await s.from('certified_referral_network').select('*').order('referral_priority',{ascending:false}).limit(100);return{items:(data||[]) as Entry[],error:error?.message||null}}
export default async function ReferralNetworkPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-emerald-700">Referral Network</p><h2 className="text-2xl font-black text-gray-900">地域別紹介ネットワーク</h2><p className="mt-1 text-sm text-gray-500">地域別に認定コーチ・認定スクールを紹介できる状態にします。公開はまだ手動確認前提です。</p></div><Link href={`/admin/ai-secretary/method-network?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">ネットワークへ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}{items.length===0&&<div className="rounded-2xl border border-dashed border-gray-300 bg-white p-6 text-sm text-gray-500">まだ紹介掲載候補はありません。認定コーチ/スクールを登録後、地域別の紹介候補として表示します。</div>}<div className="grid gap-4">{items.map(i=><article key={i.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">{i.certification_rank}</span><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">{i.entry_type}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">{i.public_profile_status}</span></div><h3 className="mt-3 text-xl font-black text-gray-900">{i.display_name}</h3><p className="mt-1 text-sm text-gray-500">{i.country} / {i.region} / {i.city} / {i.tenant_name||'テナント未設定'}</p><div className="mt-4 grid gap-2 md:grid-cols-3"><Mini label="紹介優先度" value={`${i.referral_priority}点`}/><Mini label="コーチ評価" value={`${Math.round(i.coach_score||0)}点`}/><Mini label="改善率" value={`${Math.round(i.school_improvement_rate||0)}%`}/></div><div className="mt-3 flex flex-wrap gap-2">{(i.service_types||[]).map(t=><span key={t} className="rounded-full bg-gray-50 px-3 py-1 text-xs font-bold text-gray-600">{t}</span>)}</div><p className="mt-3 text-sm leading-7 text-gray-700">{i.notes||i.contact_policy||'紹介ルール未設定'}</p></article>)}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-gray-50 p-3"><p className="text-[11px] font-black text-gray-500">{label}</p><p className="mt-1 text-lg font-black text-gray-900">{value}</p></div>}
