import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type CaseItem={id:string;anonymized_code:string;age_band:string|null;grade:string|null;position:string|null;concern:string|null;cause_summary:string|null;improvement_summary:string|null;result_summary:string|null;country:string|null;region:string|null;tags:string[]|null;publish_scope:string;status:string}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as CaseItem[],error:'supabase_not_configured'};const{data,error}=await s.from('national_case_library').select('*').order('created_at',{ascending:false}).limit(100);return{items:(data||[]) as CaseItem[],error:error?.message||null}}
export default async function NationalCasesPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-emerald-700">National Case Library</p><h2 className="text-2xl font-black text-gray-900">全国匿名症例DB</h2><p className="mt-1 text-sm text-gray-500">全スクールの症例を匿名化して、年代・ポジション・悩み・改善結果で検索できるようにします。</p></div><Link href={`/admin/ai-secretary/method-network?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">ネットワークへ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}{items.length===0&&<div className="rounded-2xl border border-dashed border-gray-300 bg-white p-6 text-sm text-gray-500">まだ全国共有用の匿名症例はありません。次に公開許可済み症例から匿名化候補を生成します。</div>}<div className="grid gap-4 md:grid-cols-2">{items.map(i=><article key={i.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">{i.anonymized_code}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">{i.status}</span><span className="text-xs text-gray-500">{i.country} / {i.region}</span></div><h3 className="mt-3 text-lg font-black text-gray-900">{i.concern||'悩み未設定'}</h3><p className="mt-2 text-sm leading-7 text-gray-700">原因: {i.cause_summary||'未入力'}</p><p className="mt-1 text-sm leading-7 text-gray-700">改善: {i.improvement_summary||'未入力'}</p><p className="mt-1 text-sm leading-7 text-gray-700">結果: {i.result_summary||'未入力'}</p><div className="mt-3 flex flex-wrap gap-2">{(i.tags||[]).map(t=><span key={t} className="rounded-full bg-gray-50 px-3 py-1 text-xs font-bold text-gray-600">{t}</span>)}</div></article>)}</div></div>}
