import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Tenant={tenant_id:string;tenant_key:string;name:string;tenant_type:string;country:string;language:string;plan_key:string;status:string;customer_count:number;inquiry_count:number;contract_count:number;active_customer_count:number;churn_customer_count:number;total_contract_amount:number;case_count:number;video_count:number;diagnosis_count:number;proposal_count:number}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Tenant[],error:'supabase_not_configured'};const{data,error}=await s.from('saas_tenant_dashboard').select('*').order('customer_count',{ascending:false}).limit(50);return{items:(data||[]) as Tenant[],error:error?.message||null}}
export default async function SaasOsPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();const total={tenants:items.length,customers:items.reduce((s,i)=>s+i.customer_count,0),diagnoses:items.reduce((s,i)=>s+i.diagnosis_count,0),revenue:items.reduce((s,i)=>s+i.total_contract_amount,0)};return <div className="space-y-6"><div className="rounded-3xl bg-gray-900 p-6 text-white"><p className="text-xs font-bold text-green-300">Yatabe Method SaaS Phase14</p><h2 className="mt-2 text-3xl font-black">谷田部メソッドOS</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-gray-300">谷田部専用AI秘書を、個人コーチ・スクール・クラブ・海外アカデミーが使えるサッカー版Salesforce/HubSpot/電子カルテへ拡張します。</p><div className="mt-5 flex flex-wrap gap-2"><Link href={`/admin/ai-secretary/tenant-dashboard?token=${encodeURIComponent(token)}`} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-gray-900">スクール別管理</Link><Link href={`/admin/ai-secretary/saas-pricing?token=${encodeURIComponent(token)}`} className="rounded-full border border-white/30 px-4 py-2 text-sm font-bold text-white">料金プラン</Link><Link href={`/admin/ai-secretary/saas-api?token=${encodeURIComponent(token)}`} className="rounded-full border border-white/30 px-4 py-2 text-sm font-bold text-white">API構想</Link></div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-4"><Kpi label="テナント" value={total.tenants}/><Kpi label="総顧客" value={total.customers}/><Kpi label="AI診断" value={total.diagnoses}/><Kpi label="契約金額" value={`${total.revenue.toLocaleString()}円`}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">SaaS機能パッケージ</h3><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-5">{['AI秘書','顧客管理','契約/回数券','症例/動画','AI診断/提案書','保護者対応','スタッフ教育','品質管理','多言語','API'].map(x=><div key={x} className="rounded-xl bg-gray-50 p-4 text-sm font-bold text-gray-800">{x}</div>)}</div></section></div>}
function Kpi({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-green-200 bg-green-50 p-5 text-green-900"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
