import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'
import { matchesCaseQuery } from '@/lib/ai-secretary/case-content'

type SearchParams=Record<string,string|string[]|undefined>
type Method={id:string;title:string;category:string;problem_pattern:string|null;parent_explanation:string|null;coaching_points:string|null;related_tags:string[]|null}
type Line={id:number;body:string;ai_summary:string|null;customer_id:string|null;customer_full_name:string|null;customer_parent_name:string|null;customer_child_name:string|null;occurred_at:string}
type Case={id:string;customer_id:string|null;case_code:string|null;problem:string|null;result:string|null;parent_feedback:string|null;tags:string[]|null;full_name:string|null;parent_name:string|null;child_name:string|null;publish_status:string;video_count:number|null}
type Video={id:string;title:string;description:string|null;youtube_url:string|null;sns_caption:string|null}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
function nameOf(i:{full_name?:string|null;parent_name?:string|null;child_name?:string|null;customer_full_name?:string|null;customer_parent_name?:string|null;customer_child_name?:string|null}){return i.full_name||i.parent_name||i.child_name||i.customer_full_name||i.customer_parent_name||i.customer_child_name||'相談者未確定'}
async function loadData(q:string){const s=getServiceClient();if(!s)return{methods:[] as Method[],lines:[] as Line[],cases:[] as Case[],videos:[] as Video[],error:'supabase_not_configured'};const [m,l,c,v]=await Promise.all([s.from('yatabe_method_knowledge').select('*').eq('status','active').limit(100),s.from('ai_secretary_line_inbox').select('*').order('occurred_at',{ascending:false}).limit(80),s.from('ai_secretary_case_assets').select('*').order('created_at',{ascending:false}).limit(300),s.from('case_videos').select('*').order('created_at',{ascending:false}).limit(100)]);const query=q.trim().toLowerCase();const methods=((m.data||[]) as Method[]).filter(x=>!query||[x.title,x.problem_pattern,x.parent_explanation,x.coaching_points,...(x.related_tags||[])].filter(Boolean).join(' ').toLowerCase().includes(query));const lines=((l.data||[]) as Line[]).filter(x=>!query||[x.body,x.ai_summary].filter(Boolean).join(' ').toLowerCase().includes(query));const cases=((c.data||[]) as Case[]).filter(x=>!query||matchesCaseQuery(x,query));const videos=((v.data||[]) as Video[]).filter(x=>!query||[x.title,x.description,x.sns_caption].filter(Boolean).join(' ').toLowerCase().includes(query));return{methods,lines,cases,videos,error:m.error?.message||l.error?.message||c.error?.message||v.error?.message||null}}
export default async function ParentConsultationPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const q=valueOf(p.q);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{methods,lines,cases,videos,error}=await loadData(q);return <div className="space-y-6"><div><p className="text-xs font-bold text-green-700">Yatabe Method Phase13</p><h2 className="text-2xl font-black text-gray-900">AI保護者相談</h2><p className="mt-1 text-sm text-gray-500">相談内容から、過去回答・谷田部メソッド・症例・動画・記事素材を提案します。</p></div><form className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><input type="hidden" name="token" value={token}/><div className="grid gap-3 md:grid-cols-[1fr_auto]"><input name="q" defaultValue={q} placeholder="例: 自信がない / セレクション不安 / 試合で消える" className="rounded-xl border border-gray-200 px-3 py-2 text-sm outline-none focus:border-green-500"/><button className="rounded-xl bg-gray-900 px-5 py-2 text-sm font-bold text-white">相談検索</button></div></form>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<Grid title="谷田部メソッド回答候補" items={methods.map(m=>({title:m.title,body:[m.problem_pattern,m.parent_explanation,m.coaching_points].filter(Boolean).join('\n\n')}))}/><Grid title="過去LINE回答候補" items={lines.map(l=>({title:nameOf(l),body:l.ai_summary||l.body,href:l.customer_id?`/admin/ai-secretary/customers/${l.customer_id}?token=${encodeURIComponent(token)}`:undefined}))}/><Grid title="類似症例" items={cases.map(c=>({title:nameOf(c),body:`${c.problem||''}\n${c.result||''}\n${c.parent_feedback||''}`,href:c.customer_id?`/admin/ai-secretary/customers/${c.customer_id}?token=${encodeURIComponent(token)}`:undefined}))}/><Grid title="関連動画" items={videos.map(v=>({title:v.title,body:v.description||v.sns_caption||'-',href:v.youtube_url||undefined,external:!!v.youtube_url}))}/></div>}
function Grid({title,items}:{title:string;items:Array<{title:string;body:string;href?:string;external?:boolean}>}){return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">{title} {items.length}件</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{items.map((i,idx)=><article key={`${i.title}-${idx}`} className="rounded-xl border border-gray-100 bg-gray-50 p-4"><h4 className="font-black text-gray-900">{i.title}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-gray-700">{i.body||'-'}</p>{i.href&&(i.external?<a href={i.href} target="_blank" rel="noreferrer" className="mt-3 inline-block rounded-full bg-white px-3 py-1 text-xs font-bold text-gray-700">開く</a>:<Link href={i.href} className="mt-3 inline-block rounded-full bg-white px-3 py-1 text-xs font-bold text-gray-700">詳細</Link>)}</article>)}{items.length===0&&<p className="text-sm text-gray-500 md:col-span-2">候補はありません。</p>}</div></section>}
