import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'
import { BusinessCandidate, candidateLabel, customerName, expectedValue, lineDraft, priorityRank, salesAction } from '@/lib/ai-secretary/business-support'

type SearchParams = Record<string, string | string[] | undefined>
function valueOf(value: string | string[] | undefined, fallback = '') { return Array.isArray(value) ? value[0] || fallback : value || fallback }
async function getSearchParams(input: Promise<SearchParams> | SearchParams | undefined) { return input ? await Promise.resolve(input) : {} }
function getServiceClient() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key || url.includes('placeholder')) return null; return createClient(url.replace(/\/+$/, ''), key) }
async function loadItems() { const supabase = getServiceClient(); if (!supabase) return { items: [] as BusinessCandidate[], error: 'supabase_not_configured' }; const { data, error } = await supabase.from('ai_secretary_sales_candidates').select('*').limit(500); return { items: ((data || []) as BusinessCandidate[]).sort((a,b)=>priorityRank(b.priority)-priorityRank(a.priority)||expectedValue(b)-expectedValue(a)), error: error?.message || null } }
export default async function SalesMeetingPage({ searchParams }: { searchParams?: Promise<SearchParams> | SearchParams }) { const params=await getSearchParams(searchParams); const token=valueOf(params.token); const requiredToken=process.env.AI_SECRETARY_READ_TOKEN; if(!requiredToken||token!==requiredToken)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>; const {items,error}=await loadItems(); if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800">AI営業会議読み取りエラー: {error}</div>; const sales=items.filter(i=>i.candidate_type!=='review_request').slice(0,8); const follow=items.filter(i=>['remaining_1','remaining_2','unused_90','private_lesson_reproposal'].includes(i.candidate_type)).slice(0,8); const reviews=items.filter(i=>i.candidate_type==='review_request').slice(0,8); const risks=items.filter(i=>['unused_90','remaining_1','expiry_7','expiry_14','expiry_30'].includes(i.candidate_type)).slice(0,8); const tasks=sales.slice(0,3); return <div className="space-y-6"><Header token={token}/><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">今日やるべきこと</h3><div className="mt-4 grid gap-3 md:grid-cols-3">{tasks.map((item,index)=><div key={`${item.customer_id}-${index}`} className="rounded-xl bg-gray-50 p-4"><p className="text-xs font-black text-green-700">{index+1}</p><Link href={`/admin/ai-secretary/customers/${item.customer_id}?token=${encodeURIComponent(token)}`} className="mt-2 block font-black text-gray-900 hover:text-green-700">{customerName(item)}</Link><p className="mt-2 text-sm leading-6 text-gray-700">{salesAction(item.candidate_type)}</p><pre className="mt-2 whitespace-pre-wrap rounded-lg bg-white p-3 text-xs leading-6 text-gray-700">{lineDraft(item)}</pre></div>)}{tasks.length===0&&<p className="text-sm text-gray-500">今日の営業タスクはまだありません。</p>}</div></section><MeetingSection title="今週売上候補" items={sales} token={token}/><MeetingSection title="今週フォロー対象" items={follow} token={token}/><MeetingSection title="今週レビュー候補" items={reviews} token={token}/><MeetingSection title="今週退会リスク" items={risks} token={token}/></div> }
function Header({ token }: { token: string }) { return <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe AI Secretary Phase8</p><h2 className="text-2xl font-black text-gray-900">AI営業会議</h2><p className="mt-1 text-sm text-gray-500">毎朝見るだけで、今日やる営業・フォロー・レビュー・退会防止を整理します。</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/ai-secretary/today-sales?token=${encodeURIComponent(token)}`} className="rounded-full border border-gray-200 bg-white px-4 py-2 text-sm font-bold text-gray-700">今日の営業</Link><Link href={`/admin/ai-secretary/dashboard?token=${encodeURIComponent(token)}`} className="rounded-full border border-gray-200 bg-white px-4 py-2 text-sm font-bold text-gray-700">ダッシュボード</Link></div></div> }
function MeetingSection({ title, items, token }: { title: string; items: BusinessCandidate[]; token: string }) { return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">{title}</h3><div className="mt-4 space-y-3">{items.map((item,index)=><Link key={`${item.customer_id}-${item.candidate_type}-${index}`} href={`/admin/ai-secretary/customers/${item.customer_id}?token=${encodeURIComponent(token)}`} className="block rounded-xl border border-gray-100 bg-gray-50 p-4 hover:border-green-300"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-gray-900 px-3 py-1 text-xs font-bold text-white">{candidateLabel(item.candidate_type)}</span><span className="rounded-full bg-yellow-100 px-2 py-1 text-xs font-bold text-yellow-700">{item.priority}</span><span className="text-xs font-bold text-gray-500">期待値 {expectedValue(item).toLocaleString()}円</span></div><p className="mt-3 font-black text-gray-900">{customerName(item)}</p><p className="mt-1 text-sm leading-6 text-gray-700">{salesAction(item.candidate_type)}</p></Link>)}{items.length===0&&<p className="text-sm text-gray-500">対象はありません。</p>}</div></section> }
