import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Tenant={tenant_id:string;tenant_key:string;name:string;tenant_type:string;country:string;language:string;plan_key:string;status:string;customer_count:number;inquiry_count:number;contract_count:number;active_customer_count:number;churn_customer_count:number;total_contract_amount:number;case_count:number;video_count:number;diagnosis_count:number;proposal_count:number}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Tenant[],error:'supabase_not_configured'};const{data,error}=await s.from('saas_tenant_dashboard').select('*').order('customer_count',{ascending:false}).limit(100);return{items:(data||[]) as Tenant[],error:error?.message||null}}
export default async function TenantDashboard({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe Method SaaS</p><h2 className="text-2xl font-black text-gray-900">スクール専用管理画面</h2><p className="mt-1 text-sm text-gray-500">テナントごとの顧客数・問い合わせ数・契約率・継続率・退会率・売上を見ます。</p></div><Link href={`/admin/ai-secretary/saas-os?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">OSへ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-4">{items.map(i=>{const contractRate=i.customer_count?Math.round((i.contract_count/i.customer_count)*100):0;const contRate=i.customer_count?Math.round((i.active_customer_count/i.customer_count)*100):0;const churnRate=i.customer_count?Math.round((i.churn_customer_count/i.customer_count)*100):0;return <article key={i.tenant_id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">{i.plan_key}</span><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">{i.tenant_type}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">{i.language}</span></div><h3 className="mt-3 text-xl font-black text-gray-900">{i.name}</h3><div className="mt-4 grid gap-2 md:grid-cols-6"><Mini label="顧客" value={i.customer_count}/><Mini label="問い合わせ" value={i.inquiry_count}/><Mini label="契約率" value={`${contractRate}%`}/><Mini label="継続率" value={`${contRate}%`}/><Mini label="退会率" value={`${churnRate}%`}/><Mini label="売上" value={`${i.total_contract_amount.toLocaleString()}円`}/></div><div className="mt-3 grid gap-2 md:grid-cols-4"><Mini label="症例" value={i.case_count}/><Mini label="動画" value={i.video_count}/><Mini label="AI診断" value={i.diagnosis_count}/><Mini label="提案書" value={i.proposal_count}/></div></article>})}</div></div>}
function Mini({label,value}:{label:string;value:number|string}){return <div className="rounded-xl bg-gray-50 p-3"><p className="text-xs font-black text-gray-500">{label}</p><p className="mt-1 text-xl font-black text-gray-900">{value}</p></div>}
