import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Row={id:string;customer_id:string|null;task_type:string;due_date:string|null;status:string;priority:string|null;ai_reason:string|null;draft_message:string|null;created_at:string|null}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Row[],error:'supabase_not_configured'};const{data,error}=await s.from('follow_tasks').select('id,customer_id,task_type,due_date,status,priority,ai_reason,draft_message,created_at').order('due_date',{ascending:true,nullsFirst:false}).limit(100);return{items:(data||[]) as Row[],error:error?.message||null}}
export default async function FollowPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe OS</p><h2 className="text-2xl font-black text-gray-900">フォロー管理</h2><p className="mt-1 text-sm text-gray-500">レビュー候補、退会防止、期限前連絡、体験後フォローをここへ集約します。</p></div><Link href={`/admin/ai-secretary/dashboard?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">今日の対応へ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-4"><Kpi label="全タスク" value={items.length}/><Kpi label="未完了" value={items.filter(i=>i.status!=='done').length}/><Kpi label="高優先" value={items.filter(i=>i.priority==='high').length}/><Kpi label="下書きあり" value={items.filter(i=>i.draft_message).length}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">フォロータスク</h3><div className="mt-4 space-y-3">{items.map(i=><div key={i.id} className="rounded-xl bg-gray-50 p-4 text-sm"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-gray-900 px-3 py-1 text-xs font-bold text-white">{i.task_type}</span><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">{i.status}</span><span className="rounded-full bg-yellow-100 px-3 py-1 text-xs font-bold text-yellow-800">{i.priority||'normal'}</span></div><p className="mt-2 font-black text-gray-900">期限: {i.due_date||'未設定'}</p>{i.ai_reason&&<p className="mt-2 rounded-lg bg-blue-50 p-3 text-blue-900">理由: {i.ai_reason}</p>}{i.draft_message&&<pre className="mt-2 whitespace-pre-wrap rounded-lg bg-white p-3 text-gray-800">{i.draft_message}</pre>}</div>)}{items.length===0&&<p className="text-sm text-gray-500">フォロータスクはまだありません。</p>}</div></section></div>}
function Kpi({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-green-200 bg-green-50 p-5 text-green-900"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
