import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Plan={plan_key:string;name:string;target_user:string|null;monthly_price_jpy:number|null;included_coaches:number|null;included_customers:number|null;included_ai_diagnoses:number|null;features:string[]|null;status:string}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Plan[],error:'supabase_not_configured'};const{data,error}=await s.from('saas_pricing_plans').select('*').eq('status','active').order('monthly_price_jpy',{ascending:true,nullsFirst:false});return{items:(data||[]) as Plan[],error:error?.message||null}}
export default async function PricingPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe Method SaaS</p><h2 className="text-2xl font-black text-gray-900">想定料金プラン</h2><p className="mt-1 text-sm text-gray-500">月額課金モデル。ライトからエンタープライズまで段階化します。</p></div><Link href={`/admin/ai-secretary/saas-plan?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">事業計画へ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(i=><article key={i.plan_key} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold text-green-700">{i.target_user}</p><h3 className="mt-2 text-xl font-black text-gray-900">{i.name}</h3><p className="mt-3 text-3xl font-black text-gray-900">{i.monthly_price_jpy?`${i.monthly_price_jpy.toLocaleString()}円/月`:'要相談'}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Mini label="コーチ" value={i.included_coaches??'∞'}/><Mini label="顧客" value={i.included_customers??'∞'}/><Mini label="AI診断" value={i.included_ai_diagnoses??'∞'}/></div><ul className="mt-4 space-y-2 text-sm text-gray-700">{(i.features||[]).map(f=><li key={f} className="rounded-lg bg-gray-50 px-3 py-2 font-bold">{f}</li>)}</ul></article>)}</div></div>}
function Mini({label,value}:{label:string;value:number|string}){return <div className="rounded-lg bg-gray-50 p-2"><p className="text-[10px] font-black text-gray-500">{label}</p><p className="font-black text-gray-900">{value}</p></div>}
