import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams = Record<string, string | string[] | undefined>
type SalesCandidate = { customer_id: string; full_name: string | null; parent_name: string | null; child_name: string | null; customer_service_type: string | null; candidate_type: string; product_name: string | null; remaining_count: number | null; effective_valid_until: string | null; expected_amount: number | null; priority: string; ai_reason: string | null }
type FollowTask = { id: number; customer_id: string; task_type: string; title: string; due_date: string | null; priority: string; ai_reason: string | null; customers?: { full_name: string | null; parent_name: string | null; child_name: string | null } | null }
type UsageCandidate = { id: number; customer_id: string | null; lesson_title: string | null; candidate_date: string; suggested_used_count: number; full_name: string | null; parent_name: string | null; child_name: string | null; ai_reason: string | null }

function getServiceClient() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key || url.includes('placeholder')) return null; return createClient(url.replace(/\/+$/, ''), key) }
function valueOf(value: string | string[] | undefined, fallback = '') { return Array.isArray(value) ? value[0] || fallback : value || fallback }
async function getSearchParams(input: Promise<SearchParams> | SearchParams | undefined) { return input ? await Promise.resolve(input) : {} }
function todayJst() { return new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Tokyo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()) }
function currentMonthStart() { const today = todayJst(); return `${today.slice(0, 7)}-01` }
function nameOf(item: { full_name?: string | null; parent_name?: string | null; child_name?: string | null }) { return item.full_name || item.parent_name || item.child_name || 'LINE顧客' }
function hrefForCustomer(id: string | null | undefined, token: string) { return id ? `/admin/ai-secretary/customers/${id}?token=${encodeURIComponent(token)}` : `/admin/ai-secretary/customers?token=${encodeURIComponent(token)}` }
function formatYen(value: number | null | undefined) { return value ? `${value.toLocaleString()}円` : '-' }
function candidateLabel(type: string) { const labels: Record<string, string> = { remaining_1: '残り1回', remaining_2: '残り2回', expiry_30: '期限30日前', expiry_14: '期限14日前', expiry_7: '期限7日前', unused_90: '90日未利用', review_request: 'レビュー依頼候補', ashiwaza_candidate: '足技塾候補', sysc_candidate: 'SYSC候補', kids_school_candidate: 'キッズ候補', private_lesson_reproposal: '個人レッスン再提案候補' }; return labels[type] || type }
function nextAction(type: string) { if (type === 'remaining_1' || type === 'remaining_2') return '継続回数券を提案'; if (type.startsWith('expiry_')) return '期限前フォロー'; if (type === 'unused_90') return '近況確認'; if (type === 'review_request') return 'レビュー依頼'; if (type === 'ashiwaza_candidate') return '足技塾を案内'; if (type === 'sysc_candidate') return 'SYSCを案内'; if (type === 'kids_school_candidate') return 'キッズスクールを案内'; return 'フォロー確認' }

async function loadTasks() {
  const supabase = getServiceClient()
  if (!supabase) return { error: 'supabase_not_configured' }
  const today = todayJst()
  const month = currentMonthStart()
  const [salesResult, followResult, usageResult] = await Promise.all([
    supabase.from('ai_secretary_sales_candidates').select('*').eq('expected_month', month).order('priority', { ascending: true }).limit(240),
    supabase.from('follow_tasks').select('*, customers(full_name,parent_name,child_name)').eq('status', 'open').order('due_date', { ascending: true, nullsFirst: false }).limit(160),
    supabase.from('ai_secretary_calendar_usage_candidates').select('*').eq('status', 'pending').order('candidate_date', { ascending: false }).limit(120),
  ])
  const error = salesResult.error?.message || followResult.error?.message || usageResult.error?.message || null
  return { error, today, sales: (salesResult.data || []) as SalesCandidate[], followTasks: (followResult.data || []) as FollowTask[], usageCandidates: (usageResult.data || []) as UsageCandidate[] }
}

export default async function TasksPage({ searchParams }: { searchParams?: Promise<SearchParams> | SearchParams }) {
  const params = await getSearchParams(searchParams)
  const token = valueOf(params.token)
  const requiredToken = process.env.AI_SECRETARY_READ_TOKEN
  if (!requiredToken || token !== requiredToken) return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>
  const data = await loadTasks()
  if (data.error) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800">Tasks読み取りエラー: {data.error}</div>
  const remaining = data.sales.filter((item) => item.candidate_type === 'remaining_1' || item.candidate_type === 'remaining_2')
  const expiring = data.sales.filter((item) => item.candidate_type === 'expiry_30' || item.candidate_type === 'expiry_14' || item.candidate_type === 'expiry_7')
  const revenue = data.sales.filter((item) => item.expected_amount || ['private_lesson_reproposal', 'ashiwaza_candidate', 'sysc_candidate', 'kids_school_candidate'].includes(item.candidate_type))
  const risk = data.sales.filter((item) => item.candidate_type === 'unused_90' || item.candidate_type === 'expiry_7')
  return <div className="space-y-6"><Header token={token} /><div className="grid gap-4 md:grid-cols-4"><CountCard label="残回数" value={remaining.length} /><CountCard label="期限" value={expiring.length} /><CountCard label="売上候補" value={revenue.length} /><CountCard label="確認待ち消化" value={data.usageCandidates.length} /></div><TaskSection title="契約・売上候補" items={revenue.slice(0, 40)} token={token} /><TaskSection title="残回数・期限" items={[...remaining, ...expiring].slice(0, 40)} token={token} /><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">回数券消化候補</h3><div className="mt-4 space-y-3">{data.usageCandidates.map((item) => <Link key={item.id} href={hrefForCustomer(item.customer_id, token)} className="block rounded-xl border border-gray-100 bg-gray-50 p-4 hover:border-green-300"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-red-100 px-2 py-1 text-red-700">確認待ち</span><span className="rounded-full bg-green-100 px-2 py-1 text-green-700">{item.suggested_used_count}回候補</span><span className="text-gray-500">{item.candidate_date}</span></div><p className="mt-3 font-black text-gray-900">{nameOf(item)}</p><p className="mt-1 text-sm text-gray-700">{item.lesson_title || 'カレンダー予定'}</p>{item.ai_reason && <p className="mt-2 text-sm leading-6 text-gray-600">{item.ai_reason}</p>}</Link>)}{data.usageCandidates.length === 0 && <p className="text-sm text-gray-500">確認待ちの消化候補はありません。</p>}</div></section><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">フォロータスク</h3><div className="mt-4 space-y-3">{data.followTasks.map((task) => <Link key={task.id} href={hrefForCustomer(task.customer_id, token)} className="block rounded-xl border border-gray-100 bg-gray-50 p-4 hover:border-green-300"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-gray-900 px-2 py-1 text-white">{task.priority}</span><span className="rounded-full bg-yellow-100 px-2 py-1 text-yellow-700">期限 {task.due_date || '-'}</span></div><p className="mt-3 font-black text-gray-900">{nameOf(task.customers || {})}</p><p className="mt-1 text-sm text-gray-700">{task.title}</p>{task.ai_reason && <p className="mt-2 text-sm leading-6 text-gray-600">{task.ai_reason}</p>}</Link>)}{data.followTasks.length === 0 && <p className="text-sm text-gray-500">フォロータスクはありません。</p>}</div></section><TaskSection title="危険候補" items={risk.slice(0, 40)} token={token} /></div>
}

function Header({ token }: { token: string }) { return <div className="rounded-3xl bg-gray-950 p-6 text-white"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-300">Yatabe Daily OS</p><h2 className="mt-1 text-3xl font-black">Tasks</h2><p className="mt-2 text-sm text-gray-300">契約、残回数、期限、フォロー、売上候補をまとめた実行リストです。</p></div><Link href={`/admin/ai-secretary/dashboard?token=${encodeURIComponent(token)}`} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-gray-950">Morningへ</Link></div></div> }
function CountCard({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold text-gray-500">{label}</p><p className="mt-2 text-3xl font-black text-gray-900">{value}</p></div> }
function TaskSection({ title, items, token }: { title: string; items: SalesCandidate[]; token: string }) { return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">{title}</h3><div className="mt-4 space-y-3">{items.map((item, index) => <Link key={`${item.customer_id}-${item.candidate_type}-${index}`} href={hrefForCustomer(item.customer_id, token)} className="block rounded-xl border border-gray-100 bg-gray-50 p-4 hover:border-green-300"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-gray-900 px-2 py-1 text-white">{candidateLabel(item.candidate_type)}</span><span className="rounded-full bg-blue-100 px-2 py-1 text-blue-700">{item.priority}</span>{item.remaining_count !== null && <span className="rounded-full bg-green-100 px-2 py-1 text-green-700">残{item.remaining_count}回</span>}{item.effective_valid_until && <span className="text-gray-500">期限 {item.effective_valid_until}</span>}</div><p className="mt-3 font-black text-gray-900">{nameOf(item)}</p><p className="mt-1 text-sm font-bold text-gray-600">次にやること: {nextAction(item.candidate_type)} / 見込み {formatYen(item.expected_amount)}</p>{item.ai_reason && <p className="mt-2 text-sm leading-6 text-gray-600">{item.ai_reason}</p>}</Link>)}{items.length === 0 && <p className="text-sm text-gray-500">対象はありません。</p>}</div></section> }
