import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Coach={id:string;coach_name:string;region:string|null;certification_rank:string;case_understanding_score:number;diagnosis_score:number;proposal_score:number;total_score:number;assessment_summary:string|null;next_training_focus:string|null;status:string}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Coach[],error:'supabase_not_configured'};const{data,error}=await s.from('method_certified_coaches').select('*').order('total_score',{ascending:false}).limit(100);return{items:(data||[]) as Coach[],error:error?.message||null}}
export default async function CoachCertificationPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-emerald-700">Certification</p><h2 className="text-2xl font-black text-gray-900">認定コーチ制度</h2><p className="mt-1 text-sm text-gray-500">AIが症例理解・診断力・提案力を評価し、ブロンズ/シルバー/ゴールド/マスター候補を管理します。</p></div><Link href={`/admin/ai-secretary/method-network?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">ネットワークへ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-4">{items.length===0&&<div className="rounded-2xl border border-dashed border-gray-300 bg-white p-6 text-sm text-gray-500">まだ認定コーチ候補はありません。次にスタッフ教育・品質管理の結果から候補を自動生成します。</div>}{items.map(i=><article key={i.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">{i.certification_rank}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">{i.status}</span><span className="text-xs text-gray-500">{i.region||'地域未設定'}</span></div><h3 className="mt-3 text-xl font-black text-gray-900">{i.coach_name}</h3><div className="mt-4 grid gap-2 md:grid-cols-4"><Mini label="症例理解" value={`${i.case_understanding_score}点`}/><Mini label="診断力" value={`${i.diagnosis_score}点`}/><Mini label="提案力" value={`${i.proposal_score}点`}/><Mini label="総合" value={`${i.total_score}点`}/></div><p className="mt-3 text-sm leading-7 text-gray-700">{i.assessment_summary||'評価コメント未入力'}</p>{i.next_training_focus&&<p className="mt-2 rounded-xl bg-yellow-50 p-3 text-sm font-bold text-yellow-900">次の育成テーマ: {i.next_training_focus}</p>}</article>)}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-gray-50 p-3"><p className="text-[11px] font-black text-gray-500">{label}</p><p className="mt-1 text-lg font-black text-gray-900">{value}</p></div>}
