import Link from 'next/link'

type SearchParams=Record<string,string|string[]|undefined>
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
const finalMenu=[['ダッシュボード','dashboard','今日やること'],['未対応LINE','line-inbox','LINE返信下書き'],['顧客','customers','顧客マスタ'],['売上','revenue','売上候補'],['契約','contracts','契約/契約書'],['回数券','tickets','残回数/期限'],['フォロー','follow','フォロータスク'],['症例','cases','症例DB'],['動画','videos','動画DB'],['AI診断','diagnosis-center','診断/原因/改善'],['AI提案書','proposals','提案書'],['設定','integrations','外部連携']]
const categories=[
  ['完成',['既存LINE Webhook受信','LINEメッセージ保存','未対応LINE一覧','Basic認証 + token','契約書PDF生成の土台']],
  ['実運用可能',['未対応LINE確認','AI要約/返信下書き確認','顧客マスタ確認','売上候補確認','契約/回数券/フォローの手動管理','今日の対応ダッシュボード']],
  ['開発中',['Gmail取り込み','Googleカレンダー取り込み','AI人物カルテ','自然文検索','症例/動画/記事/SNS生成','認定制度','世界展開/サッカー病院']],
  ['未着手',['LINE自動送信','メール自動送信','Stripe課金','テナント別ログイン','外部公開APIキー','本格ベクトル検索','監査ログ']],
]
const debts=[['重複画面','sales-meeting/today-salesはdashboard/revenueへ、reviews/churn-riskはfollowへ統合予定'],['要注意API','/api/debug-envは本番では閉じるか管理者限定にする'],['送信機能','lib/line.tsのpush送信は送信フェーズまで封印'],['DB','将来設計テーブルは削除せず、実データ投入後に判断'],['環境変数','LINE_AUTO_REPLY_ENABLEDはfalse維持。Gmail/Google OAuthは未完成']]
const future=[['SaaS/認定','saas-os, tenant-dashboard, method-network, certification系'],['世界展開','global-expansion, global-diagnosis, overseas-camps, ai-translation'],['サッカー病院','soccer-hospital, medical-records, prescriptions, case-lab, soccer-university']]
export default async function OsMapPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const q=`?token=${encodeURIComponent(token)}`;return <div className="space-y-6"><div className="rounded-3xl bg-gray-950 p-6 text-white"><p className="text-xs font-bold text-green-300">PhaseX Integration</p><h2 className="mt-2 text-3xl font-black">谷田部OSマップ</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-gray-300">増えた機能を、毎日使う12メニューへ整理します。詳細機能や将来構想はこのOSマップから辿れるようにします。</p></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">最終12メニュー</h3><div className="mt-4 grid gap-3 md:grid-cols-3 lg:grid-cols-4">{finalMenu.map(([label,path,desc],idx)=><Link key={path} href={`/admin/ai-secretary/${path}${q}`} className="rounded-xl border border-gray-100 bg-gray-50 p-4 hover:border-green-300 hover:bg-green-50"><p className="text-xs font-black text-green-700">{idx+1}</p><h4 className="mt-1 font-black text-gray-900">{label}</h4><p className="mt-1 text-xs text-gray-500">{desc}</p></Link>)}</div></section><section className="grid gap-4 md:grid-cols-2">{categories.map(([title,items])=><div key={title} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="font-black text-gray-900">{title}</h3><ul className="mt-3 space-y-2 text-sm text-gray-700">{(items as string[]).map(x=><li key={x} className="rounded-lg bg-gray-50 px-3 py-2">{x}</li>)}</ul></div>)}</section><section className="rounded-2xl border border-yellow-200 bg-yellow-50 p-5 text-yellow-950"><h3 className="font-black">技術負債・整理対象</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{debts.map(([k,v])=><div key={k} className="rounded-xl bg-white/70 p-4"><p className="text-sm font-black">{k}</p><p className="mt-1 text-sm leading-7">{v}</p></div>)}</div></section><section className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-blue-950"><h3 className="font-black">将来構想は通常メニューから分離</h3><div className="mt-3 grid gap-3 md:grid-cols-3">{future.map(([k,v])=><div key={k} className="rounded-xl bg-white/70 p-4"><p className="text-sm font-black">{k}</p><p className="mt-1 text-sm leading-7">{v}</p></div>)}</div></section></div>}
