import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Cell=string|number|boolean|string[]|number[]|null|undefined
type Row=Record<string, Cell>
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Row[],error:'supabase_not_configured'};const{data,error}=await s.from('ai_prescriptions').select('id,prescription_title,priority_order,training_menu,expected_frequency,review_after_days,status,created_at').order('created_at',{ascending:false}).limit(100);return{items:(data||[]) as Row[],error:error?.message||null}}
export default async function Page({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-sky-700">AI Prescriptions</p><h2 className="text-2xl font-black text-gray-900">AI処方箋</h2><p className="mt-1 text-sm text-gray-500">診断結果から、やるべき練習・優先順位・動画・関連記事・症例を提示します。</p></div><Link href={`/admin/ai-secretary/soccer-hospital?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">戻る</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}{items.length===0&&<div className="rounded-2xl border border-dashed border-gray-300 bg-white p-6 text-sm text-gray-500">まだデータはありません。DB反映後、該当データが入るとここに表示されます。</div>}<div className="grid gap-4">{items.map(i=><article key={i.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">{String(i['prescription_title']||i.id).slice(0,80)}</h3><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">頻度: {format(i['expected_frequency'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">確認日数: {format(i['review_after_days'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">状態: {format(i['status'])}</span></div><div className="mt-4 space-y-2 text-sm leading-7 text-gray-700">{i['training_menu']&&<p><span className="font-black text-gray-900">training_menu: </span>{format(i['training_menu'])}</p>}</div></article>)}</div></div>}
function format(v:Cell){if(v==null||v==='')return '未設定';if(Array.isArray(v))return v.join(', ');return String(v)}
