import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Dashboard={tenant_count:number;certified_coach_count:number;certified_school_count:number;national_case_count:number;referral_entry_count:number;avg_coach_score:number;avg_retention_rate:number;avg_diagnosis_accuracy:number}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{item:null as Dashboard|null,error:'supabase_not_configured'};const{data,error}=await s.from('method_network_dashboard').select('*').maybeSingle();return{item:data as Dashboard|null,error:error?.message||null}}
export default async function MethodNetworkPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{item,error}=await loadData();const q=`?token=${encodeURIComponent(token)}`;return <div className="space-y-6"><div className="rounded-3xl bg-emerald-950 p-6 text-white"><p className="text-xs font-bold text-emerald-200">Yatabe Method Network Phase15</p><h2 className="mt-2 text-3xl font-black">谷田部メソッド認定ネットワーク</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-emerald-100">SaaSを、認定コーチ・認定スクール・全国匿名症例DB・地域紹介ネットワークへ発展させます。谷田部が直接対応できない地域でも、メソッド品質を保って届けるための本部画面です。</p><div className="mt-5 flex flex-wrap gap-2">{[['コーチ認定','coach-certification'],['スクール認定','school-certification'],['全国症例DB','national-cases'],['紹介ネットワーク','referral-network']].map(([label,path])=><Link key={path} href={`/admin/ai-secretary/${path}${q}`} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-emerald-950">{label}</Link>)}</div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-4"><Kpi label="テナント" value={item?.tenant_count??0}/><Kpi label="認定コーチ" value={item?.certified_coach_count??0}/><Kpi label="認定スクール" value={item?.certified_school_count??0}/><Kpi label="全国症例" value={item?.national_case_count??0}/><Kpi label="紹介掲載候補" value={item?.referral_entry_count??0}/><Kpi label="平均コーチ評価" value={`${Math.round(item?.avg_coach_score??0)}点`}/><Kpi label="平均継続率" value={`${Math.round(item?.avg_retention_rate??0)}%`}/><Kpi label="診断精度" value={`${Math.round(item?.avg_diagnosis_accuracy??0)}%`}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">Phase15で管理するもの</h3><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-5">{['症例理解評価','診断力評価','提案力評価','認定ランク','匿名症例共有','AI精度改善','地域別紹介','スクール評価','品質保証','全国展開'].map(x=><div key={x} className="rounded-xl bg-gray-50 p-4 text-sm font-bold text-gray-800">{x}</div>)}</div></section></div>}
function Kpi({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-950"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
