import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type School={id:string;school_name:string;country:string|null;region:string|null;certification_rank:string;retention_rate:number;improvement_rate:number;review_score:number;contract_rate:number;assessment_summary:string|null;required_improvement:string|null;status:string}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as School[],error:'supabase_not_configured'};const{data,error}=await s.from('method_certified_schools').select('*').order('created_at',{ascending:false}).limit(100);return{items:(data||[]) as School[],error:error?.message||null}}
export default async function SchoolCertificationPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-emerald-700">Certification</p><h2 className="text-2xl font-black text-gray-900">認定スクール制度</h2><p className="mt-1 text-sm text-gray-500">継続率・改善率・レビュー・契約率を見て、スクール品質を認定します。</p></div><Link href={`/admin/ai-secretary/method-network?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">ネットワークへ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-4">{items.map(i=><article key={i.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">{i.certification_rank}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">{i.status}</span><span className="text-xs text-gray-500">{i.country} / {i.region||'地域未設定'}</span></div><h3 className="mt-3 text-xl font-black text-gray-900">{i.school_name}</h3><div className="mt-4 grid gap-2 md:grid-cols-4"><Mini label="継続率" value={`${Math.round(i.retention_rate||0)}%`}/><Mini label="改善率" value={`${Math.round(i.improvement_rate||0)}%`}/><Mini label="レビュー" value={`${i.review_score||0}`}/><Mini label="契約率" value={`${Math.round(i.contract_rate||0)}%`}/></div><p className="mt-3 text-sm leading-7 text-gray-700">{i.assessment_summary||'評価コメント未入力'}</p>{i.required_improvement&&<p className="mt-2 rounded-xl bg-yellow-50 p-3 text-sm font-bold text-yellow-900">改善条件: {i.required_improvement}</p>}</article>)}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-gray-50 p-3"><p className="text-[11px] font-black text-gray-500">{label}</p><p className="mt-1 text-lg font-black text-gray-900">{value}</p></div>}
