import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Row={id:string;contract_id:string|null;used_at:string|null;usage_count:number|null;memo:string|null;created_at:string|null}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Row[],error:'supabase_not_configured'};const{data,error}=await s.from('ticket_usage').select('id,contract_id,used_at,usage_count,memo,created_at').order('created_at',{ascending:false}).limit(100);return{items:(data||[]) as Row[],error:error?.message||null}}
export default async function TicketsPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe OS</p><h2 className="text-2xl font-black text-gray-900">回数券管理</h2><p className="mt-1 text-sm text-gray-500">回数券消化履歴、残回数、有効期限管理の統合入口です。</p></div><Link href={`/admin/ai-secretary/contracts?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">契約へ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-3"><Kpi label="消化履歴" value={items.length}/><Kpi label="消化回数合計" value={items.reduce((s,i)=>s+(i.usage_count||0),0)}/><Kpi label="確認待ち" value="カレンダー候補連携"/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">消化履歴</h3><div className="mt-4 space-y-3">{items.map(i=><div key={i.id} className="rounded-xl bg-gray-50 p-4 text-sm"><p className="font-black text-gray-900">{i.used_at||i.created_at||'日付未設定'} / {i.usage_count||0}回</p><p className="mt-1 text-gray-600">契約ID: {i.contract_id||'未設定'}</p>{i.memo&&<p className="mt-1 text-gray-700">{i.memo}</p>}</div>)}{items.length===0&&<p className="text-sm text-gray-500">回数券消化履歴はまだありません。</p>}</div></section></div>}
function Kpi({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-green-200 bg-green-50 p-5 text-green-900"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
