import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Cell=string|number|boolean|string[]|number[]|null|undefined
type Row=Record<string, Cell>
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Row[],error:'supabase_not_configured'};const{data,error}=await s.from('overseas_camps').select('id,camp_name,country_code,city,starts_on,ends_on,capacity,participant_count,contract_status_summary,payment_status_summary,parent_support_notes,review_status_summary,status,created_at').order('created_at',{ascending:false}).limit(100);return{items:(data||[]) as Row[],error:error?.message||null}}
export default async function Page({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-sky-700">Overseas Camps</p><h2 className="text-2xl font-black text-gray-900">海外キャンプ管理</h2><p className="mt-1 text-sm text-gray-500">参加者管理・契約管理・支払い管理・保護者対応・レビュー管理の入口です。</p></div><Link href={`/admin/ai-secretary/global-expansion?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">戻る</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}{items.length===0&&<div className="rounded-2xl border border-dashed border-gray-300 bg-white p-6 text-sm text-gray-500">まだデータはありません。DB反映後、該当データが入るとここに表示されます。</div>}<div className="grid gap-4">{items.map(i=><article key={i.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">{String(i['camp_name']||i.id).slice(0,80)}</h3><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">国: {format(i['country_code'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">都市: {format(i['city'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">開始: {format(i['starts_on'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">終了: {format(i['ends_on'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">参加者: {format(i['participant_count'])}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">状態: {format(i['status'])}</span></div><div className="mt-4 space-y-2 text-sm leading-7 text-gray-700">{i['contract_status_summary']&&<p><span className="font-black text-gray-900">contract_status_summary: </span>{format(i['contract_status_summary'])}</p>}{i['payment_status_summary']&&<p><span className="font-black text-gray-900">payment_status_summary: </span>{format(i['payment_status_summary'])}</p>}{i['parent_support_notes']&&<p><span className="font-black text-gray-900">parent_support_notes: </span>{format(i['parent_support_notes'])}</p>}{i['review_status_summary']&&<p><span className="font-black text-gray-900">review_status_summary: </span>{format(i['review_status_summary'])}</p>}</div></article>)}</div></div>}
function format(v:Cell){if(v==null||v==='')return '未設定';if(Array.isArray(v))return v.join(', ');return String(v)}
