import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams = Record<string, string | string[] | undefined>
type CoachItem = { customer_id: string; full_name: string | null; parent_name: string | null; child_name: string | null; grade: string | null; team_name: string | null; service_type: string | null; status: string | null; owner_name: string | null; next_reservation_at: string | null; memo: string | null; ai_profile_overview: string | null; pain_points: string | null; caution_notes: string | null; recommended_service: string | null; case_count: number | null; diagnosis_count: number | null; latest_concern: string | null; latest_next_step: string | null }
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(input:Promise<SearchParams>|SearchParams|undefined){return input?await Promise.resolve(input):{}}
function nameOf(i:CoachItem){return i.full_name||i.child_name||i.parent_name||'LINE顧客'} function formatDate(v:string|null){return v?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'-'}
async function loadData(){const s=getServiceClient(); if(!s)return{items:[] as CoachItem[],error:'supabase_not_configured'}; const {data,error}=await s.from('ai_coach_lesson_support').select('*').order('next_reservation_at',{ascending:true,nullsFirst:false}).limit(200); return{items:(data||[]) as CoachItem[],error:error?.message||null}}
export default async function CoachSupportPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><Header token={token}/>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-3"><Kpi label="レッスン支援対象" value={items.length}/><Kpi label="注意事項あり" value={items.filter(i=>i.caution_notes).length}/><Kpi label="診断あり" value={items.filter(i=>(i.diagnosis_count||0)>0).length}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">スタッフ用レッスン前カルテ</h3><div className="mt-4 space-y-3">{items.map(i=><article key={i.customer_id} className="rounded-xl border border-gray-100 bg-gray-50 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">担当 {i.owner_name||'未設定'}</span><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">次回 {formatDate(i.next_reservation_at)}</span><span className="rounded-full bg-gray-900 px-3 py-1 text-xs font-bold text-white">症例 {i.case_count||0} / 診断 {i.diagnosis_count||0}</span></div><h4 className="mt-3 text-lg font-black text-gray-900">{nameOf(i)}</h4><p className="mt-1 text-sm text-gray-500">{i.grade||'-'} / {i.team_name||'-'} / {i.service_type||'-'}</p></div><Link href={`/admin/ai-secretary/customers/${i.customer_id}?token=${encodeURIComponent(token)}`} className="rounded-full border border-gray-200 bg-white px-3 py-2 text-xs font-bold text-gray-700">顧客詳細</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Block label="悩み・現在地" value={i.pain_points||i.latest_concern||i.ai_profile_overview}/><Block label="改善案・次の一手" value={i.latest_next_step||i.recommended_service||i.memo}/><Block label="注意事項" value={i.caution_notes}/><Block label="スタッフ確認" value="谷田部メソッドの説明、成功体験、保護者への共有を忘れない。"/></div></article>)}{items.length===0&&<p className="text-sm text-gray-500">対象顧客はまだありません。</p>}</div></section></div>}
function Header({token}:{token:string}){return <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe Method Phase13</p><h2 className="text-2xl font-black text-gray-900">AIコーチ支援</h2><p className="mt-1 text-sm text-gray-500">スタッフがレッスン前に、顧客情報・悩み・症例・改善案・注意事項を確認します。</p></div><Link href={`/admin/ai-secretary/staff-training?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">スタッフ教育へ</Link></div>}
function Kpi({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-green-200 bg-green-50 p-5 text-green-900"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>}
function Block({label,value}:{label:string;value:string|null}){return <div className="rounded-xl bg-white p-4"><p className="text-xs font-black text-gray-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-gray-800">{value||'-'}</p></div>}
