import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Line={id:number;customer_id:string|null;body:string;ai_summary:string|null;ai_reply_draft:string|null;manual_memo:string|null;status:string;customer_full_name:string|null;customer_parent_name:string|null;customer_child_name:string|null;occurred_at:string}
type Proposal={id:string;customer_id:string|null;title:string|null;current_issue:string|null;recommended_service:string|null;recommended_plan:string|null;body:string|null;status:string;created_at:string;customers?:{full_name:string|null;parent_name:string|null;child_name:string|null}|null}
type Review={id:string;source_type:string;issue_type:string;issue_summary:string|null;yatabe_method_suggestion:string|null;status:string;created_at:string}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
function nameOf(i:{customer_full_name?:string|null;customer_parent_name?:string|null;customer_child_name?:string|null;customers?:{full_name:string|null;parent_name:string|null;child_name:string|null}|null}){return i.customer_full_name||i.customer_parent_name||i.customer_child_name||i.customers?.full_name||i.customers?.parent_name||i.customers?.child_name||'LINE顧客'}
function formatDate(v:string|null){return v?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'-'}
async function loadData(){const s=getServiceClient();if(!s)return{lines:[] as Line[],proposals:[] as Proposal[],reviews:[] as Review[],error:'supabase_not_configured'};const [l,p,r]=await Promise.all([s.from('ai_secretary_line_inbox').select('*').order('occurred_at',{ascending:false}).limit(120),s.from('ai_proposals').select('*, customers(full_name,parent_name,child_name)').order('created_at',{ascending:false}).limit(100),s.from('quality_control_reviews').select('*').order('created_at',{ascending:false}).limit(100)]);return{lines:(l.data||[]) as Line[],proposals:(p.data||[]) as Proposal[],reviews:(r.data||[]) as Review[],error:l.error?.message||p.error?.message||r.error?.message||null}}
function lineIssues(i:Line){const issues:string[]=[];if(!i.ai_summary)issues.push('説明不足: AI要約なし');if(!i.ai_reply_draft)issues.push('対応漏れ: 返信下書きなし');if((i.ai_reply_draft||'').length<40)issues.push('説明不足: 返信が短い');if(!i.manual_memo&&i.status==='needs_review')issues.push('対応漏れ: 手動メモなし');return issues}
function proposalIssues(i:Proposal){const issues:string[]=[];if(!i.current_issue)issues.push('説明不足: 現在の悩みなし');if(!i.recommended_service)issues.push('提案不足: サービス提案なし');if(!i.recommended_plan)issues.push('提案不足: プラン提案なし');if((i.body||'').length<200)issues.push('説明不足: 提案書本文が短い');return issues}
export default async function QualityControlPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{lines,proposals,reviews,error}=await loadData();const lineRisks=lines.map(i=>({item:i,issues:lineIssues(i)})).filter(x=>x.issues.length);const proposalRisks=proposals.map(i=>({item:i,issues:proposalIssues(i)})).filter(x=>x.issues.length);return <div className="space-y-6"><div><p className="text-xs font-bold text-green-700">Yatabe Method Phase13</p><h2 className="text-2xl font-black text-gray-900">AI品質管理</h2><p className="mt-1 text-sm text-gray-500">谷田部メソッド基準で、説明不足・提案不足・対応漏れを検出します。自動評価確定はしません。</p></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-3"><Kpi label="LINE品質リスク" value={lineRisks.length}/><Kpi label="提案書品質リスク" value={proposalRisks.length}/><Kpi label="レビュー記録" value={reviews.length}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">LINE対応チェック</h3><div className="mt-4 space-y-3">{lineRisks.map(({item,issues})=><article key={item.id} className="rounded-xl border border-gray-100 bg-gray-50 p-4"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-700">{issues[0]}</span><span className="text-xs font-bold text-gray-500">{formatDate(item.occurred_at)}</span></div><h4 className="mt-3 font-black text-gray-900">{nameOf(item)}</h4><p className="mt-2 text-sm leading-7 text-gray-700">{issues.join(' / ')}</p>{item.customer_id&&<Link href={`/admin/ai-secretary/customers/${item.customer_id}?token=${encodeURIComponent(token)}`} className="mt-3 inline-block rounded-full bg-white px-3 py-1 text-xs font-bold text-gray-700">顧客詳細</Link>}</article>)}{lineRisks.length===0&&<p className="text-sm text-gray-500">LINE品質リスクはありません。</p>}</div></section><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">提案書チェック</h3><div className="mt-4 space-y-3">{proposalRisks.map(({item,issues})=><article key={item.id} className="rounded-xl border border-gray-100 bg-gray-50 p-4"><span className="rounded-full bg-yellow-100 px-3 py-1 text-xs font-bold text-yellow-700">{issues[0]}</span><h4 className="mt-3 font-black text-gray-900">{item.title||nameOf(item)}</h4><p className="mt-2 text-sm leading-7 text-gray-700">{issues.join(' / ')}</p></article>)}{proposalRisks.length===0&&<p className="text-sm text-gray-500">提案書品質リスクはありません。</p>}</div></section></div>}
function Kpi({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>}
