import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Dash={medical_record_count:number;prescription_count:number;prediction_count:number;research_finding_count:number;course_count:number;avg_improvement_probability:number;avg_estimated_weeks:number;avg_estimated_lesson_count:number}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{item:null as Dash|null,error:'supabase_not_configured'};const{data,error}=await s.from('soccer_hospital_dashboard').select('*').maybeSingle();return{item:data as Dash|null,error:error?.message||null}}
export default async function SoccerHospitalPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{item,error}=await loadData();const q=`?token=${encodeURIComponent(token)}`;return <div className="space-y-6"><div className="rounded-3xl bg-red-950 p-6 text-white"><p className="text-xs font-bold text-red-200">Phase17 Football Technique Hospital</p><h2 className="mt-2 text-3xl font-black">サッカー技術の病院</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-red-100">症状、診断、処方、改善、症例研究までをつなげ、世界中の選手が「なぜ上手くならないのか」を検索できる状態を作ります。</p><div className="mt-5 flex flex-wrap gap-2">{[['電子カルテ','medical-records'],['AI処方箋','prescriptions'],['改善予測','improvement-prediction'],['症例研究所','case-lab'],['サッカー大学','soccer-university']].map(([l,path])=><Link key={path} href={`/admin/ai-secretary/${path}${q}`} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-red-950">{l}</Link>)}</div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<div className="grid gap-3 md:grid-cols-4"><Kpi label="電子カルテ" value={item?.medical_record_count??0}/><Kpi label="AI処方箋" value={item?.prescription_count??0}/><Kpi label="改善予測" value={item?.prediction_count??0}/><Kpi label="研究発見" value={item?.research_finding_count??0}/><Kpi label="講座" value={item?.course_count??0}/><Kpi label="平均改善確率" value={`${Math.round(item?.avg_improvement_probability??0)}%`}/><Kpi label="平均改善期間" value={`${Math.round(item?.avg_estimated_weeks??0)}週`}/><Kpi label="必要回数" value={`${Math.round(item?.avg_estimated_lesson_count??0)}回`}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">病院モデル</h3><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-7">{['症状入力','動画提出','AI診断','原因分析','処方箋','改善予測','症例研究'].map(x=><div key={x} className="rounded-xl bg-gray-50 p-4 text-center text-sm font-black text-gray-800">{x}</div>)}</div></section></div>}
function Kpi({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-950"><p className="text-xs font-bold opacity-70">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
