import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'

type SearchParams=Record<string,string|string[]|undefined>
type Staff={staff_name:string;assigned_customers:number;assigned_cases:number;continuing_customers:number;review_candidates:number;training_records:number;avg_success_score:number|null}
function getServiceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||url.includes('placeholder'))return null;return createClient(url.replace(/\/+$/,''),key)}
function valueOf(v:string|string[]|undefined,f=''){return Array.isArray(v)?v[0]||f:v||f} async function getSearchParams(i:Promise<SearchParams>|SearchParams|undefined){return i?await Promise.resolve(i):{}}
async function loadData(){const s=getServiceClient();if(!s)return{items:[] as Staff[],error:'supabase_not_configured'};const{data,error}=await s.from('staff_training_summary').select('*').order('assigned_customers',{ascending:false}).limit(100);return{items:(data||[]) as Staff[],error:error?.message||null}}
export default async function StaffTrainingPage({searchParams}:{searchParams?:Promise<SearchParams>|SearchParams}){const p=await getSearchParams(searchParams);const token=valueOf(p.token);const required=process.env.AI_SECRETARY_READ_TOKEN;if(!required||token!==required)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>;const{items,error}=await loadData();return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe Method Phase13</p><h2 className="text-2xl font-black text-gray-900">AIスタッフ教育</h2><p className="mt-1 text-sm text-gray-500">担当症例・継続率・レビュー候補・教育記録を見て、スタッフ育成ポイントを整理します。</p></div><Link href={`/admin/ai-secretary/coach-support?token=${encodeURIComponent(token)}`} className="rounded-full bg-gray-900 px-4 py-2 text-sm font-bold text-white">AIコーチ支援へ</Link></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">読み取りエラー: {error}</div>}<section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">スタッフ別サマリー</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{items.map(i=>{const rate=i.assigned_customers?Math.round((i.continuing_customers/i.assigned_customers)*100):0;return <article key={i.staff_name} className="rounded-xl border border-gray-100 bg-gray-50 p-4"><h4 className="text-lg font-black text-gray-900">{i.staff_name}</h4><div className="mt-3 grid grid-cols-2 gap-2"><Mini label="担当顧客" value={i.assigned_customers}/><Mini label="担当症例" value={i.assigned_cases}/><Mini label="継続率" value={`${rate}%`}/><Mini label="レビュー候補" value={i.review_candidates}/></div><p className="mt-3 rounded-lg bg-white p-3 text-sm leading-7 text-gray-700">教育ポイント: 成功症例を1つ選び、谷田部メソッドの説明順・保護者共有・次提案の漏れを確認。</p></article>})}{items.length===0&&<p className="text-sm text-gray-500">スタッフデータはまだありません。</p>}</div></section></div>}
function Mini({label,value}:{label:string;value:number|string|null}){return <div className="rounded-lg bg-white p-3"><p className="text-xs font-black text-gray-500">{label}</p><p className="mt-1 text-2xl font-black text-gray-900">{value??'-'}</p></div>}
