import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'
import { BusinessCandidate, customerName, lineDraft, priorityClass, serviceLabel } from '@/lib/ai-secretary/business-support'

type SearchParams = Record<string, string | string[] | undefined>
function valueOf(value: string | string[] | undefined, fallback = '') { return Array.isArray(value) ? value[0] || fallback : value || fallback }
async function getSearchParams(input: Promise<SearchParams> | SearchParams | undefined) { return input ? await Promise.resolve(input) : {} }
function getServiceClient() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key || url.includes('placeholder')) return null; return createClient(url.replace(/\/+$/, ''), key) }
async function loadItems() { const supabase = getServiceClient(); if (!supabase) return { items: [] as BusinessCandidate[], error: 'supabase_not_configured' }; const { data, error } = await supabase.from('ai_secretary_sales_candidates').select('*').eq('candidate_type','review_request').limit(200); return { items: (data || []) as BusinessCandidate[], error: error?.message || null } }
export default async function ReviewsPage({ searchParams }: { searchParams?: Promise<SearchParams> | SearchParams }) { const params=await getSearchParams(searchParams); const token=valueOf(params.token); const requiredToken=process.env.AI_SECRETARY_READ_TOKEN; if(!requiredToken||token!==requiredToken)return <div className="rounded-2xl border border-yellow-200 bg-yellow-50 p-6 text-yellow-900">閲覧トークンが必要です。</div>; const {items,error}=await loadItems(); if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800">レビュー候補読み取りエラー: {error}</div>; return <div className="space-y-6"><Header token={token}/><div className="grid gap-3 md:grid-cols-3"><Kpi label="レビュー候補" value={items.length}/><Kpi label="満足度高め候補" value={items.filter(i=>i.customer_status==='continuing'||i.customer_status==='enrolled').length}/><Kpi label="文面生成済み" value={items.length}/></div><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-black text-gray-900">レビュー依頼候補</h3><div className="mt-4 space-y-3">{items.map((item,index)=><div key={`${item.customer_id}-${index}`} className="rounded-xl border border-gray-100 bg-gray-50 p-4"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${priorityClass(item.priority)}`}>{item.priority}</span><span className="rounded-full bg-green-100 px-2 py-1 text-xs font-bold text-green-700">{serviceLabel(item.customer_service_type)}</span></div><Link href={`/admin/ai-secretary/customers/${item.customer_id}?token=${encodeURIComponent(token)}`} className="mt-3 block text-base font-black text-gray-900 hover:text-green-700">{customerName(item)}</Link><p className="mt-2 rounded-lg bg-blue-50 p-3 text-sm leading-7 text-blue-900">提案理由: 継続・入会中で関係性が残っているため、レビュー依頼候補です。</p><pre className="mt-2 whitespace-pre-wrap rounded-lg border border-gray-100 bg-white p-3 text-sm leading-7 text-gray-800">{lineDraft(item)}</pre></div>)}{items.length===0&&<p className="text-sm text-gray-500">レビュー候補はまだありません。</p>}</div></section></div> }
function Header({ token }: { token: string }) { return <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold text-green-700">Yatabe AI Secretary Phase8</p><h2 className="text-2xl font-black text-gray-900">AIレビュー獲得支援</h2><p className="mt-1 text-sm text-gray-500">満足度が高そうな家庭・成果が出た家庭へ、レビュー依頼文を準備します。自動送信はしません。</p></div><Link href={`/admin/ai-secretary/sales-meeting?token=${encodeURIComponent(token)}`} className="rounded-full border border-gray-200 bg-white px-4 py-2 text-sm font-bold text-gray-700">AI営業会議へ</Link></div> }
function Kpi({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-gray-200 bg-white p-5"><p className="text-xs font-bold text-gray-500">{label}</p><p className="mt-2 text-3xl font-black text-gray-900">{value}</p></div> }
